issue #195: Implement new mutect2 variant calling strategy
epam/fonda pull request #207
Opened 2021-05-11 14:26 UTC by kamyshova

Resolves #195
The pull request provides implementation of the new gatk4 mutect2 variant calling strategy:

- Added new templates after mutect2 tool:
  - GetPileupSummaries
  - CalculateContamination
  - LearnReadOrientation
  - SortBamout
  - FilterMutectCalls
  - FilterAlignmentArtifacts
- Realignment was skipped for gatk4 mutect2

2021-05-11 17:51 UTC, syansanofi commented
@kamyshova 
**Different issues:**
I am getting -normal NA when using tumor only.   
Vardict & strelka2 all run without matching control with "NA" set as control.

2021-05-12 10:35 UTC, kamyshova commented
@syansanofi Fixed

2021-05-14 19:00 UTC, syansanofi requested changes

2021-05-14 19:00 UTC, syansanofi commented on src/main/java/com/epam/fonda/tools/impl/FilterMutectCalls.java
> +                .contamTable(contamTable)
Should be sample specific contamination table

`.contamTable(format("%s/%s.contamination.table", outputDir, sampleName))`

2021-05-14 20:23 UTC, kamyshova commented on src/main/java/com/epam/fonda/tools/impl/FilterMutectCalls.java
> +                .contamTable(contamTable)
Fixed `CalculateContaminationOutput` in `CalculateContamination` tool

2021-05-17 18:58 UTC, syansanofi approved these changes

2021-05-18 09:14 UTC, merged