GitHub Actions workflow for Fonda
epam/fonda pull request #228
Opened 2021-11-01 17:51 UTC by madmongoose

Stored in .github/workflows/main.yml;
Start triggers: push to develop branch or manually start in Actions page;
500mb storage;
2000 min per month for jobs;
Total concurrent Linux jobs: 20;
Maximum concurrent macOS jobs: 5;
Artefact storage on a jobs web page: from 0 to 90 days;

Supported runners and hardware resources
Hardware specification for Windows and Linux virtual machines:
* 2-core CPU
* 7 GB of RAM memory
* 14 GB of SSD disk space
Hardware specification for macOS virtual machines:
* 3-core CPU
* 14 GB of RAM memory
* 14 GB of SSD disk space

Action steps:
1. Runing docker with ubuntu-latest;
2. Git clone repository;
3. Setup Java JDK 8 (temirin prebuild);
4. Building with Gradle (./gradlew -PbuildNumber=ga.${{ github.run_number }}.${{ github.sha }} build zip --no-daemon);
5. Testing with Gradle (./gradlew jacocoTestReport)
6. Uploading artefact to job web page in zip;
7. Geting AWS credentials from GitHub Secrets;
8. Copying an artefact to AWS S3 Bucket to folder like a branch with name fonda-2.0.0.ga.${{ github.run_number }}.${{ github.sha }}.zip (for example fonda-2.0.0.ga.468b49764403fe39c964a470d270389341dc3014.zip);
9. Automatic clean tasks.

2021-11-01 17:55 UTC, sidoruka requested changes
Please also update add the Github Action releases URL to the README (where the user can grab the distro besides the S3)

2021-11-01 17:55 UTC, sidoruka commented on README.md
> +[![Build status](https://github.com/madmongoose/fonda/workflows/build/badge.svg?branch=develop)](https://github.com/madmongoose/fonda/actions)
Please change to EPAM repository, instead of the fork URL

2021-11-08 10:43 UTC, madmongoose commented
Added release action to workflow;
Added releases page to the README;
All commits were squashed.

2021-11-08 14:06 UTC, kamyshova requested changes

2021-11-08 14:06 UTC, kamyshova commented on README.md
> +[![Build status](https://github.com/epam/fonda/workflows/build/badge.svg?branch=develop)](https://github.com/madmongoose/fonda/actions)
Change URL to EPAM repository, please

2021-11-08 14:06 UTC, kamyshova commented on .github/workflows/fonda-ci.yml
> +          cache: "gradle"
Should we use cache?

2021-11-08 14:06 UTC, kamyshova commented on .github/workflows/fonda-ci.yml
> +      - "docs/**"
Do you mean `doc` instead of `docs`?

2021-11-08 14:26 UTC, kamyshova approved these changes

2021-11-08 14:27 UTC, merged